[package]
name = "todo-list-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.7"
colored = "2.1.0"
rusqlite = "0.31.0"

