[local]
# keep deleted tasks for how many days
keep_deleted_tasks = 3
# keep deleted tasks for how many days
keep_done_tasks = 3

[global]
# keep deleted tasks for how many days
keep_deleted_tasks = 3
# keep deleted tasks for how many days
keep_done_tasks = 3
